theme = "tokyonight"

[editor]
line-number = "relative"
scroll-lines = 1
auto-pairs = false
true-color = true

[editor.cursor-shape]
insert = "underline"
normal = "block"
select = "block"

[editor.file-picker]
hidden = true

[editor.lsp]
display-messages = true

[keys.normal]
g = { a = "code_action" } # Maps `ga` to show possible code actions
"ret" = ["move_line_down", "goto_first_nonwhitespace"] # Maps the enter key to move to start of next line
X = "extend_line_above"
D = "delete_char_backward"

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

